### ISSUE TITLE
args,type_net in train_wide_resnet.py undefined

### ISSUE THREAD

**Issue by ThomasHagebols** [AMLab-Amsterdam/L0_regularization#1]
It seems that there is a little bug in the code which causes the training to stop after one epoch at line 172. The args,type_net in train_wide_resnet.py is not defined. I think that the args,type_net argument should be added right after defining the argument parser in line 17.

**Comment by clouizos** [comment]
Thanks for catching that up! That was a remnant from the original version of the code that I forgot to remove.
