### ISSUE TITLE
[Question] On equation(26) in the paper

### ISSUE THREAD

**Issue by zhangtj1996** [AMLab-Amsterdam/L0_regularization#2]
Dear authors,

Please have a look at third term in equation(26) in the paper.  I don't think the normalization (Q(1)-Q(0)) should be included. Please check if I were wrong.

Best,
Tianjian

**Comment by clouizos** [comment]
Hi Tianjian,

At eq. 26 we are using (Q(1) - Q(0)) * truncated_q_in_(0, 1). If you replace the truncated q with its actual expression truncated_q = normal_q / (Q(1) - Q(0)) then indeed the (Q(1) - Q(0)) will cancel out. We chose to employ the first expression as it more clearly stated how the probability mass is divided. 

Hope this clears any confusion.

Best,
Christos

**Comment by zhangtj1996** [comment]
Thanks, the response makes sense : )
