### ISSUE TITLE
Cannot reproduce WRN experiments

### ISSUE THREAD

**Issue by shurjobanerjee** [AMLab-Amsterdam/L0_regularization#6]
The wide-resnet experiments provided in the repository does not appear to replicate the results in the paper.
Upon running the experiment, neither the expected L0 norm or the expected flops changes at all
![image](https://user-images.githubusercontent.com/5953190/83678615-07150f00-a5ac-11ea-9491-0557557e65fb.png)

This is corroborated by the following excerpt from the paper The State of Sparsity in Deep Neural Networks (https://arxiv.org/pdf/1902.09574.pdf). 
![Selection_051](https://user-images.githubusercontent.com/5953190/83678522-e056d880-a5ab-11ea-90de-2c33fcb10714.png)

Would greatly appreciate any feedback on how to utilize this repository to replicate L0 regularization on Wide Resnets for the CIFAR datasets.

**Comment by clouizos** [comment]
Hi, 

Apologies for the late reply, I am not at the university anymore and I don't check this repo. Did you make sure to play around with the lamba hyperparameter that controls the regularization strength? It is that one which dictates whether pruning actually happens. As for the issue from https://arxiv.org/pdf/1902.09574.pdf; this was a different thing and was referring to how the counting of FLOPs for convolutional layers was actually happening in this branch, which was incorrect, and not about whether the model was pruning during training. From a quick check the probabilities of activating the gates do decrease after a couple of iterations with, e.g., a lamba of 1 so the expected FLOPs do decrease. As this branch is provided as is and is not maintained, feel free to use the one from https://github.com/google-research/google-research/tree/master/state_of_sparsity. 

Hope this helped! I will be closing this issue.
